apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    k8s-app: nginx
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: nginx
    spec:
      serviceAccountName: nginx
      containers:
      - image: arizon/nginx-arm:latest
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf 
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
status: {}
