apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    k8s-app: nginx
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: nginx
    spec:
      containers:
      - image: minimolnet/arizon-nginx-hello-world:latest
        imagePullPolicy: Never
        name: nginx
        resources: {}
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/conf.d/
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf 
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
status: {}
